/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#009b50",
        "outline-variant": "#c4c6cf",
        "tertiary": "#000802",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001c3a",
        "secondary-fixed": "#d4e4f6",
        "on-tertiary-fixed": "#00210c",
        "primary-fixed-dim": "#afc8f0",
        "on-surface-variant": "#43474e",
        "on-secondary-container": "#556474",
        "primary-container": "#001f3f",
        "surface-container": "#eeeeee",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface": "#f9f9f9",
        "primary-fixed": "#d4e3ff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e2e2e2",
        "on-error": "#ffffff",
        "tertiary-fixed": "#6bfe9c",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed-variant": "#005228",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadada",
        "tertiary-fixed-dim": "#4ae183",
        "inverse-primary": "#afc8f0",
        "on-background": "#1a1c1c",
        "secondary-fixed-dim": "#b8c8da",
        "on-primary-container": "#6f88ad",
        "primary": "#000613",
        "outline": "#74777f",
        "inverse-on-surface": "#f0f1f1",
        "surface-variant": "#e2e2e2",
        "on-primary-fixed-variant": "#2f486a",
        "on-surface": "#1a1c1c",
        "background": "#f9f9f9",
        "on-secondary-fixed-variant": "#394857",
        "secondary": "#50606f",
        "secondary-container": "#d1e1f4",
        "surface-tint": "#476083",
        "surface-container-high": "#e8e8e8",
        "inverse-surface": "#2f3131",
        "tertiary-container": "#00250e",
        "on-secondary-fixed": "#0d1d2a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        lg: "24px",
        unit: "4px",
        xxl: "80px",
        "container-max": "1200px",
        xl: "48px",
        xs: "4px",
        md: "16px",
        gutter: "24px",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
}
